// @ts-check
/**
 * Generates Valibot schemas from OpenAPI components.schemas.
 * Output: src/generated/schemas.ts
 */
const fs = require("node:fs");
const path = require("node:path");

const SWAGGER_PATH = path.resolve(__dirname, "../swagger.json");
const OUTPUT_PATH = path.resolve(__dirname, "../src/generated/schemas.ts");

function toCamelCase(str) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

/**
 * Build a valibot expression for an OpenAPI schema node.
 * @param {object} schema
 * @param {Set<string>} allSchemaNames - available $ref targets
 * @returns {string} valibot expression source code
 */
function schemaToValibot(schema, allSchemaNames) {
  if (!schema) return "v.unknown()";

  // $ref
  if (schema.$ref) {
    const refName = schema.$ref.split("/").pop();
    if (allSchemaNames.has(refName)) {
      return `${toCamelCase(refName)}Schema`;
    }
    return "v.unknown()";
  }

  // oneOf / anyOf
  if (schema.oneOf) {
    const variants = schema.oneOf.map((s) => schemaToValibot(s, allSchemaNames));
    return `v.union([${variants.join(", ")}])`;
  }
  if (schema.anyOf) {
    const variants = schema.anyOf.map((s) => schemaToValibot(s, allSchemaNames));
    return `v.union([${variants.join(", ")}])`;
  }

  // enum
  if (schema.enum) {
    const values = schema.enum.map((e) =>
      typeof e === "string" ? `"${e}"` : String(e),
    );
    return `v.picklist([${values.join(", ")}])`;
  }

  // type-based
  switch (schema.type) {
    case "string": {
      const pipes = [];
      if (schema.minLength != null) pipes.push(`v.minLength(${schema.minLength})`);
      if (schema.maxLength != null) pipes.push(`v.maxLength(${schema.maxLength})`);
      if (schema.pattern) pipes.push(`v.regex(/${schema.pattern}/)`);
      if (pipes.length > 0) return `v.pipe(v.string(), ${pipes.join(", ")})`;
      return "v.string()";
    }
    case "number":
    case "integer":
      return "v.number()";
    case "boolean":
      return "v.boolean()";
    case "array": {
      const items = schemaToValibot(schema.items || {}, allSchemaNames);
      return `v.array(${items})`;
    }
    case "object": {
      // additionalProperties only (Record type)
      if (schema.additionalProperties && !schema.properties) {
        const valSchema = schemaToValibot(schema.additionalProperties, allSchemaNames);
        return `v.record(v.string(), ${valSchema})`;
      }

      if (!schema.properties || Object.keys(schema.properties).length === 0) {
        if (schema.additionalProperties) {
          const valSchema = schemaToValibot(schema.additionalProperties, allSchemaNames);
          return `v.record(v.string(), ${valSchema})`;
        }
        return "v.object({})";
      }

      const required = new Set(schema.required || []);
      const fields = [];
      for (const [key, propSchema] of Object.entries(schema.properties)) {
        let expr = schemaToValibot(propSchema, allSchemaNames);
        if (propSchema.nullable) {
          expr = `v.nullable(${expr})`;
        }
        if (!required.has(key)) {
          expr = `v.optional(${expr})`;
        }
        fields.push(`  ${key}: ${expr},`);
      }
      return `v.object({\n${fields.join("\n")}\n})`;
    }
    default:
      return "v.unknown()";
  }
}

function generate() {
  if (!fs.existsSync(SWAGGER_PATH)) {
    console.warn("⚠ swagger.json not found. Creating stub schemas.ts");
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, 'export {};\n');
    return;
  }

  const swagger = JSON.parse(fs.readFileSync(SWAGGER_PATH, "utf-8"));
  const schemas = swagger.components?.schemas || {};
  const allSchemaNames = new Set(Object.keys(schemas));

  // Topological sort: schemas that reference other schemas should come after
  const sorted = topologicalSort(schemas, allSchemaNames);

  const lines = [
    "// Auto-generated by generate-schemas.js — DO NOT EDIT",
    'import * as v from "valibot";',
    "",
  ];

  for (const name of sorted) {
    const schema = schemas[name];
    const varName = `${toCamelCase(name)}Schema`;
    const typeName = name;
    const expr = schemaToValibot(schema, allSchemaNames);
    lines.push(`export const ${varName} = ${expr};`);
    lines.push(`export type ${typeName} = v.InferOutput<typeof ${varName}>;`);
    lines.push("");
  }

  // Generate inline schemas used in operations (e.g. createRoom response)
  generateInlineSchemas(swagger, lines, allSchemaNames);

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, lines.join("\n"));
  console.log(`✓ Generated ${sorted.length} schemas to ${OUTPUT_PATH}`);
}

function topologicalSort(schemas, allSchemaNames) {
  const visited = new Set();
  const result = [];

  function visit(name) {
    if (visited.has(name)) return;
    visited.add(name);
    const deps = getDeps(schemas[name], allSchemaNames);
    for (const dep of deps) {
      if (schemas[dep]) visit(dep);
    }
    result.push(name);
  }

  for (const name of Object.keys(schemas)) {
    visit(name);
  }
  return result;
}

function getDeps(schema, allSchemaNames) {
  const deps = new Set();
  if (!schema) return deps;
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop();
    if (allSchemaNames.has(name)) deps.add(name);
  }
  if (schema.properties) {
    for (const prop of Object.values(schema.properties)) {
      for (const d of getDeps(prop, allSchemaNames)) deps.add(d);
    }
  }
  if (schema.items) {
    for (const d of getDeps(schema.items, allSchemaNames)) deps.add(d);
  }
  if (schema.oneOf) {
    for (const s of schema.oneOf) {
      for (const d of getDeps(s, allSchemaNames)) deps.add(d);
    }
  }
  if (schema.anyOf) {
    for (const s of schema.anyOf) {
      for (const d of getDeps(s, allSchemaNames)) deps.add(d);
    }
  }
  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    for (const d of getDeps(schema.additionalProperties, allSchemaNames)) deps.add(d);
  }
  return deps;
}

/**
 * Generate schemas for inline response/request bodies that aren't in components.schemas.
 */
function generateInlineSchemas(swagger, lines, allSchemaNames) {
  const paths = swagger.paths || {};
  for (const [, methods] of Object.entries(paths)) {
    for (const [, op] of Object.entries(methods)) {
      if (!op || typeof op !== "object" || !op.operationId) continue;
      const opId = op.operationId;

      // Response schema (200/201)
      for (const code of ["200", "201"]) {
        const respSchema = op.responses?.[code]?.content?.["application/json"]?.schema;
        if (respSchema && !respSchema.$ref && respSchema.type === "object" && respSchema.properties) {
          const varName = `${toCamelCase(opId)}ResponseSchema`;
          const typeName = `${opId}Response`;
          const expr = schemaToValibot(respSchema, allSchemaNames);
          lines.push(`export const ${varName} = ${expr};`);
          lines.push(`export type ${typeName} = v.InferOutput<typeof ${varName}>;`);
          lines.push("");
        }
      }

      // Inline request body
      const reqSchema = op.requestBody?.content?.["application/json"]?.schema;
      if (reqSchema && !reqSchema.$ref && reqSchema.type === "object" && reqSchema.properties) {
        const varName = `${toCamelCase(opId)}BodySchema`;
        const typeName = `${opId}Body`;
        const expr = schemaToValibot(reqSchema, allSchemaNames);
        lines.push(`export const ${varName} = ${expr};`);
        lines.push(`export type ${typeName} = v.InferOutput<typeof ${varName}>;`);
        lines.push("");
      }
    }
  }
}

generate();
